import type { ToolOutputSchema } from './contract.js';

export type OutputSchema = ToolOutputSchema;

const STRING_DESCRIPTION_ALIASES: Record<string, string> = {
  日期: '日期文本',
  时间: '时间文本',
  阳历: '阳历日期文本',
  农历: '农历日期文本',
  公历: '公历日期文本',
  问题: '占问文本',
  占问: '占问文本',
  占问事项: '占问文本',
  性别: '性别标记',
  日主: '日主天干',
  命主五行: '日主所属五行',
  出生地: '出生地点文本',
  日干支: '当日干支',
  流日十神: '当日十神',
  生肖: '生肖名称',
  节气: '所属节气',
  冲煞: '冲煞信息',
  彭祖百忌: '彭祖百忌内容',
  胎神: '胎神方位说明',
  描述: '描述文本',
  方位: '方位信息',
  财神: '财神方位',
  喜神: '喜神方位',
  福神: '福神方位',
  阳贵人: '阳贵人方位',
  阴贵人: '阴贵人方位',
  建除十二值星: '当日建除值星',
  天神: '天神名称',
  天神类型: '天神类别',
  天神吉凶: '天神吉凶判断',
  二十八星宿: '当日星宿',
  星宿吉凶: '星宿吉凶判断',
  星宿歌诀: '星宿歌诀原文',
  日柱纳音: '日柱纳音',
  时辰: '时辰名称',
  计算模式: '计算模式名称',
  说明: '补充说明',
  坐标: '经纬度坐标文本',
  本命时区: '本命时区名称',
  本命时刻: '本命时间文本',
  流运时刻: '流运时间文本',
  黄道体系: '黄道体系名称',
  宫制: '宫制名称',
  星座: '星座名称',
  黄经: '绝对黄经与星座内度数',
  宫位: '宫位名称',
  逆行: '逆行标记',
  对象: '相位对象名称',
  相位: '相位名称',
  因素: '因素名称',
  流运星体: '流运因素名称',
  起点: '相位起点',
  终点: '相位终点',
  起点黄经: '星座起点黄经',
  四柱: '四柱干支',
  干支: '干支文本',
  天干: '天干文本',
  地支: '地支文本',
  五行: '五行属性',
  纳音: '纳音属性',
  十神: '十神关系',
  地势: '十二长生状态',
  气性: '藏干气性',
  卦辞: '卦辞原文',
  象辞: '象辞原文',
  上卦: '上卦名称',
  下卦: '下卦名称',
  上卦五行: '上卦五行',
  下卦五行: '下卦五行',
  整卦五行: '整卦五行',
  本卦: '本卦卦名',
  变卦: '变卦卦名',
  互卦: '互卦卦名',
  错卦: '错卦卦名',
  综卦: '综卦卦名',
  体卦: '体卦名称',
  用卦: '用卦名称',
  体卦旺衰: '体卦月令旺衰',
  用卦旺衰: '用卦月令旺衰',
  体互旺衰: '体互月令旺衰',
  用互旺衰: '用互月令旺衰',
  变卦旺衰: '变卦月令旺衰',
  所属: '所属位置',
  结果: '结果文本',
  总结: '总结文本',
  方法: '起卦方式',
  方法系: '方法体系',
  实际采用的子方式: '实际起卦子方式',
  起卦时间: '起卦时间文本',
  原始文本: '原始文本',
  取用文本: '取用文本',
  取句方式: '取句方式',
  柱: '柱位',
  月支: '月令地支',
  关系: '关系类型',
  关系表达式: '关系表达式',
  阶段: '推演阶段',
  落点: '阶段落点',
  表达式: '推演表达式',
  课式: '课式名称',
  昼夜: '昼夜标记',
  月将: '月将地支',
  月将名称: '月将名称',
  本命: '本命信息',
  行年: '行年信息',
  课别: '课别名称',
  乘将: '乘将信息',
  上神: '上神名称',
  下神: '下神名称',
  传序: '传序名称',
  天将: '天将名称',
  遁干: '遁干',
  旺衰: '旺衰状态',
  长生十二神: '长生十二神状态',
  建除: '建除状态',
  卦宫: '卦宫名称',
  爻名: '爻名',
  爻辞: '爻辞原文',
  爻位: '爻位名称',
  六神: '六神名称',
  动静: '动静状态',
  空亡: '空亡状态',
  化变: '化变关系',
  世应: '世应关系',
  类型: '类型名称',
  结果五行: '结果五行',
  细节级别: '细节级别',
  年柱: '年柱干支',
  月柱: '月柱干支',
  日柱: '日柱干支',
  时柱: '时柱干支',
  出生时间: '出生时间文本',
  是否闰月: '闰月标记',
  工具名: '推荐工具名',
  起运详情: '起运说明',
  起运信息: '起运说明',
  地支主气十神: '地支主气十神',
  释义: '释义文本',
  太乙名: '太乙星名',
  神性: '星性类别',
  北斗名: '北斗星名',
  映射参考: '跨体系映射参考',
  能量交互: '能量关系说明',
  主诀原文: '主诀原文',
  使用提示: '使用提示',
  牌阵: '牌阵名称',
  随机种子: '随机种子文本',
  位置: '位置说明',
  塔罗牌: '塔罗牌名称',
  状态: '状态标记',
  元素: '元素属性',
  星象对应: '星象对应',
  对应塔罗: '对应塔罗牌',
  年份: '对应年份',
  层次: '运限层次',
  时间段或备注: '时间段备注',
  落入本命宫位: '对应本命宫位',
  查询类型: '查询类型',
  判断目标: '判断目标',
  发射宫位: '发射宫位',
  发射宫干支: '发射宫干支',
  本宫: '本宫名称',
  对宫: '对宫名称',
  目标宫位: '目标宫位',
  目标日期: '目标日期文本',
  五行局: '五行局名称',
  命主: '命主名称',
  身主: '身主名称',
  命主星: '命主星名称',
  身主星: '身主星名称',
  钟表时间: '原始钟表时间',
  真太阳时: '校正后的真太阳时',
  跨日偏移: '跨日偏移说明',
  时辰序号: '时辰序号',
  日上落点: '日上落点',
  时上最终落点: '时上落点',
  月上起落点: '月上起落点',
  最终落宫: '最终落宫',
  性质: '性质说明',
  盘式: '盘式名称',
  定局法: '定局法名称',
  局式: '局式名称',
  三元: '三元信息',
  旬首: '旬首信息',
  值符: '值符名称',
  值使: '值使名称',
  节气范围: '节气区间',
  宫名: '宫名',
  宫头星座: '宫头星座',
  宫头黄经: '宫头黄经',
  八神: '八神名称',
  九星: '九星名称',
  八门: '八门名称',
  宫位五行: '宫位五行',
  九星五行: '九星五行',
  八门五行: '八门五行',
  天盘天干五行: '天盘天干五行',
  地盘天干五行: '地盘天干五行',
  天盘天干: '天盘天干',
  地盘天干: '地盘天干',
  宫旺衰: '宫位旺衰',
  驿马地支: '驿马地支',
  驿马宫位: '驿马所在宫位',
  本卦六亲: '本卦六亲',
  本卦纳甲: '本卦纳甲',
  本卦五行: '本卦五行',
  星曜: '星曜名称',
  星名: '星曜名称',
  亮度: '星曜亮度',
  四化: '四化名称',
  离心自化: '离心自化',
  向心自化: '向心自化',
  生年天干: '生年天干',
};

const NUMBER_DESCRIPTION_ALIASES: Record<string, string> = {
  数量: '数量值',
  左半笔画: '左半笔画数',
  右半笔画: '右半笔画数',
  大单位: '大单位数值',
  小单位: '小单位数值',
  指定动爻: '指定动爻序号',
  候选序号: '候选编号',
  候选总数: '候选数量',
  年龄: '对应年龄',
  起运年龄: '起运年龄',
  起始年份: '起始年份',
  起运年份: '起运年份',
  流年年份: '流年年份',
  流年: '流年年份',
  年份: '对应年份',
  宫位索引: '宫位索引',
  宫位序号: '宫位序号',
  时辰序号: '时辰序号',
  经度: '经度值',
  校正分钟: '校正分钟数',
  真太阳时索引: '真太阳时索引',
  容许度: '相位容许度',
  实际夹角: '实际夹角度数',
};

const BOOLEAN_DESCRIPTION_ALIASES: Record<string, string> = {
  resolved: '解析成功标记',
};

const ARRAY_DESCRIPTION_ALIASES: Record<string, string> = {
  宜: '宜事项列表',
  忌: '忌事项列表',
  吉神: '吉神列表',
  凶煞: '凶煞列表',
  神煞: '神煞列表',
  空亡: '空亡列表',
  涉及地支: '涉及地支列表',
  藏干: '藏干列表',
  原局关系: '与原局的关系列表',
  太岁关系: '与太岁的关系列表',
  流年列表: '流年列表',
  小运列表: '小运列表',
  大运列表: '大运列表',
  动爻: '动爻列表',
  动爻爻辞: '动爻爻辞列表',
  参与者: '参与者列表',
  位置: '涉及位置列表',
  六爻全盘: '六爻爻位列表',
  组合关系: '组合关系列表',
  冲合转换: '冲合转换列表',
  反吟伏吟: '反吟伏吟信息列表',
  背景基调: '背景基调列表',
  核心基调: '核心基调列表',
  运限四化: '运限四化列表',
  吉星分布: '吉星分布',
  煞星分布: '煞星分布',
  '桃花/文星': '桃花与文星分布',
  岁前十二星: '岁前十二星列表',
  将前十二星: '将前十二星列表',
  附加课体: '附加课体列表',
  虚岁列表: '虚岁列表',
  流年虚岁: '流年虚岁列表',
  小限虚岁: '小限虚岁列表',
  本命主星: '本命主要因素列表',
  当前流运触发: '当前流运触发列表',
  附加点与交点: '附加点与交点列表',
  宫位宫头: '宫头信息列表',
  本命完整相位: '本命完整相位列表',
  流运完整相位: '流运完整相位列表',
  黄道分界: '黄道分界列表',
  四柱: '四柱列表',
  十二宫: '十二宫位列表',
  宫位状态: '宫位状态列表',
  格局: '格局列表',
  全局格局: '全局格局列表',
  地支: '地支列表',
  宫位: '宫位列表',
  缺少信息: '缺少字段列表',
};

const OBJECT_DESCRIPTION_ALIASES: Record<string, string> = {
  真太阳时: '真太阳时校正信息',
  日九星: '日九星信息',
  生年四化: '生年四化信息',
  日空: '日空信息',
  时空: '时空信息',
  驿马: '驿马信息',
  卦盘: '卦盘信息',
  衍生卦: '衍生卦信息',
  全局互动: '全局互动信息',
  元信息: '元信息',
  问卜设定: '问卜设定信息',
  求问者生命数字: '求问者生命数字信息',
  人格牌: '人格牌信息',
  灵魂牌: '灵魂牌信息',
  年度牌: '年度牌信息',
  下一步排盘建议: '下一步排盘建议',
  矩阵宫位: '矩阵宫位信息',
  关键状态: '关键状态信息',
  外部时空环境: '外部时空环境',
  问卜与时空底盘: '问卜与时空底盘',
  核心物理关系: '核心物理关系',
  古典参考: '古典参考',
  体用分析: '体用分析',
  月令环境: '月令环境',
  基本信息: '基本信息',
  扩展信息: '扩展信息',
  命盘锚点: '命盘锚点',
  基础坐标: '基础坐标',
  空亡信息: '空亡信息',
};

function normalizeOutputDescription(kind: 'string' | 'number' | 'boolean' | 'array' | 'object', description?: string): string | undefined {
  const trimmed = description?.trim();
  if (!trimmed) return undefined;

  const aliasMaps = {
    string: STRING_DESCRIPTION_ALIASES,
    number: NUMBER_DESCRIPTION_ALIASES,
    boolean: BOOLEAN_DESCRIPTION_ALIASES,
    array: ARRAY_DESCRIPTION_ALIASES,
    object: OBJECT_DESCRIPTION_ALIASES,
  } satisfies Record<typeof kind, Record<string, string>>;

  const alias = aliasMaps[kind][trimmed];
  if (alias) return alias;

  if (kind === 'array') {
    if (/(列表|分布)$/u.test(trimmed)) return trimmed;
    return `${trimmed}列表`;
  }

  if (kind === 'object') {
    if (/(信息|详情|坐标|关系|矩阵|参考|设定|环境|底盘)$/u.test(trimmed)) return trimmed;
    return `${trimmed}信息`;
  }

  if (kind === 'number') {
    if (/(数值|数量|年份|年龄|分钟|序号|索引|度数|经度|纬度)$/u.test(trimmed)) return trimmed;
    return `${trimmed}数值`;
  }

  if (kind === 'boolean') {
    if (/(标记|状态|是否)$/u.test(trimmed)) return trimmed;
    return `${trimmed}标记`;
  }

  if (/(文本|信息|说明|原文|名称|属性|标记|干支|日期|时间|方位|类型|关系|基调|编码|用途|模式|状态)$/u.test(trimmed)) {
    return trimmed;
  }

  return `${trimmed}文本`;
}

export const str = (description?: string) => ({ type: 'string', ...(normalizeOutputDescription('string', description) ? { description: normalizeOutputDescription('string', description) } : {}) });
export const num = (description?: string) => ({ type: 'number', ...(normalizeOutputDescription('number', description) ? { description: normalizeOutputDescription('number', description) } : {}) });
export const bool = (description?: string) => ({ type: 'boolean', ...(normalizeOutputDescription('boolean', description) ? { description: normalizeOutputDescription('boolean', description) } : {}) });
export const arr = (items: Record<string, unknown>, description?: string) => ({
  type: 'array',
  items,
  ...(normalizeOutputDescription('array', description) ? { description: normalizeOutputDescription('array', description) } : {}),
});
export const obj = (properties: Record<string, unknown>, description?: string): OutputSchema => ({
  type: 'object',
  properties,
  ...(normalizeOutputDescription('object', description) ? { description: normalizeOutputDescription('object', description) } : {}),
});

export const trueSolarTimeSchema = obj({
  clockTime: str('钟表时间'),
  trueSolarTime: str('真太阳时'),
  longitude: num('经度'),
  correctionMinutes: num('校正分钟数'),
}, '真太阳时信息');

export const hiddenStemSchema = obj({
  stem: str('藏干天干'),
  tenGod: str('藏干十神'),
  qiType: str('气性'),
});

export const branchRelationSchema = obj({
  type: str('关系类型'),
  branches: arr(str(), '涉及地支'),
  description: str('关系描述'),
});

export const liunianItemSchema = obj({
  year: num('流年年份'),
  age: num('年龄'),
  ganZhi: str('干支'),
  gan: str('天干'),
  zhi: str('地支'),
  tenGod: str('天干十神'),
  nayin: str('纳音'),
  hiddenStems: arr(hiddenStemSchema, '藏干'),
  diShi: str('地势'),
  shenSha: arr(str(), '神煞'),
  branchRelations: arr(branchRelationSchema, '地支关系'),
  taiSui: arr(str(), '太岁关系'),
});

export const dayunItemSchema = obj({
  startYear: num('起始年份'),
  startAge: num('起运年龄'),
  ganZhi: str('干支'),
  stem: str('天干'),
  branch: str('地支'),
  tenGod: str('十神'),
  branchTenGod: str('地支主气十神'),
  hiddenStems: arr(hiddenStemSchema, '藏干'),
  diShi: str('地势'),
  naYin: str('纳音'),
  shenSha: arr(str(), '神煞'),
  branchRelations: arr(branchRelationSchema, '原局关系'),
  liunianList: arr(liunianItemSchema, '流年列表'),
});
